/**
 * Danh mục văn bản – tài liệu mẫu. Tệp này chỉ chứa dữ liệu (không truy cập CSDL)
 * để script sinh tệp PDF minh họa có thể dùng lại.
 */
export interface SeedDocument {
  number: string;
  title: string;
  docType: string;
  docGroup: "legal" | "direction" | "guidance" | "report" | "standard" | "form";
  issuer: string;
  signer: string | null;
  issuedDate: string;
  effectiveDate: string | null;
  field: string | null;
  project?: string;
  summary: string;
  fileName: string;
  /** true: văn bản của cơ quan có thẩm quyền – tệp PDF chỉ là bản giới thiệu, dẫn chiếu nguồn chính thức */
  external: boolean;
  /** Các đoạn nội dung minh họa trong tệp PDF */
  body: string[];
  downloadCount: number;
}

const INSTITUTE = "Viện Công nghệ số và Chuyển đổi số quốc gia";

export const DOCUMENTS: SeedDocument[] = [
  {
    number: "60/2024/QH15",
    title: "Luật Dữ liệu",
    docType: "Luật",
    docGroup: "legal",
    issuer: "Quốc hội",
    signer: null,
    issuedDate: "2024-11-30",
    effectiveDate: "2025-07-01",
    field: "du-lieu",
    summary: "Quy định về dữ liệu số; xây dựng, phát triển, bảo vệ, quản trị, xử lý, sử dụng dữ liệu số; Trung tâm dữ liệu quốc gia, Cơ sở dữ liệu tổng hợp quốc gia; sản phẩm, dịch vụ về dữ liệu.",
    fileName: "luat-du-lieu-60-2024-qh15.pdf",
    external: true,
    body: [
      "Luật Dữ liệu được Quốc hội khóa XV thông qua ngày 30/11/2024, có hiệu lực thi hành từ ngày 01/7/2025.",
      "Luật quy định về dữ liệu số; xây dựng, phát triển, bảo vệ, quản trị, xử lý, sử dụng dữ liệu số; Trung tâm dữ liệu quốc gia, Cơ sở dữ liệu tổng hợp quốc gia; sản phẩm, dịch vụ về dữ liệu; quản lý nhà nước về dữ liệu và quyền, nghĩa vụ, trách nhiệm của cơ quan, tổ chức, cá nhân có liên quan.",
    ],
    downloadCount: 1284,
  },
  {
    number: "71/2025/QH15",
    title: "Luật Công nghiệp công nghệ số",
    docType: "Luật",
    docGroup: "legal",
    issuer: "Quốc hội",
    signer: null,
    issuedDate: "2025-06-14",
    effectiveDate: "2026-01-01",
    field: "cong-nghe-so",
    summary: "Quy định về công nghiệp công nghệ số, bao gồm hoạt động công nghiệp công nghệ số, sản phẩm, dịch vụ công nghệ số, trí tuệ nhân tạo, tài sản số và các biện pháp bảo đảm phát triển công nghiệp công nghệ số.",
    fileName: "luat-cong-nghiep-cong-nghe-so-71-2025-qh15.pdf",
    external: true,
    body: [
      "Luật Công nghiệp công nghệ số được Quốc hội khóa XV thông qua tại Kỳ họp thứ 9, có hiệu lực thi hành từ ngày 01/01/2026.",
      "Luật điều chỉnh hoạt động công nghiệp công nghệ số; phát triển sản phẩm, dịch vụ công nghệ số; trí tuệ nhân tạo; tài sản số và các biện pháp bảo đảm phát triển công nghiệp công nghệ số.",
    ],
    downloadCount: 967,
  },
  {
    number: "93/2025/QH15",
    title: "Luật Khoa học, công nghệ và đổi mới sáng tạo",
    docType: "Luật",
    docGroup: "legal",
    issuer: "Quốc hội",
    signer: null,
    issuedDate: "2025-06-27",
    effectiveDate: "2025-10-01",
    field: null,
    summary: "Quy định về hoạt động khoa học, công nghệ và đổi mới sáng tạo; quyền, nghĩa vụ của tổ chức, cá nhân tham gia; biện pháp bảo đảm phát triển khoa học, công nghệ và đổi mới sáng tạo.",
    fileName: "luat-khoa-hoc-cong-nghe-doi-moi-sang-tao-93-2025-qh15.pdf",
    external: true,
    body: [
      "Luật Khoa học, công nghệ và đổi mới sáng tạo được Quốc hội khóa XV thông qua tại Kỳ họp thứ 9.",
      "Luật quy định về hoạt động khoa học, công nghệ và đổi mới sáng tạo; quyền và nghĩa vụ của tổ chức, cá nhân; các biện pháp bảo đảm phát triển khoa học, công nghệ và đổi mới sáng tạo.",
    ],
    downloadCount: 742,
  },
  {
    number: "57-NQ/TW",
    title: "Nghị quyết về đột phá phát triển khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia",
    docType: "Nghị quyết",
    docGroup: "direction",
    issuer: "Bộ Chính trị",
    signer: null,
    issuedDate: "2024-12-22",
    effectiveDate: null,
    field: "chuyen-doi-so",
    summary: "Xác định phát triển khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia là đột phá quan trọng hàng đầu, động lực chính để phát triển nhanh lực lượng sản xuất hiện đại.",
    fileName: "nghi-quyet-57-nq-tw.pdf",
    external: true,
    body: [
      "Nghị quyết số 57-NQ/TW ngày 22/12/2024 của Bộ Chính trị về đột phá phát triển khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia.",
      "Nghị quyết xác định phát triển khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia là đột phá quan trọng hàng đầu, là động lực chính để phát triển nhanh lực lượng sản xuất hiện đại, hoàn thiện quan hệ sản xuất, đổi mới phương thức quản trị quốc gia.",
    ],
    downloadCount: 2315,
  },
  {
    number: "749/QĐ-TTg",
    title: "Quyết định phê duyệt “Chương trình Chuyển đổi số quốc gia đến năm 2025, định hướng đến năm 2030”",
    docType: "Quyết định",
    docGroup: "direction",
    issuer: "Thủ tướng Chính phủ",
    signer: null,
    issuedDate: "2020-06-03",
    effectiveDate: "2020-06-03",
    field: "chuyen-doi-so",
    summary: "Phê duyệt Chương trình Chuyển đổi số quốc gia với mục tiêu kép: phát triển Chính phủ số, kinh tế số, xã hội số và hình thành các doanh nghiệp công nghệ số Việt Nam có năng lực đi ra toàn cầu.",
    fileName: "quyet-dinh-749-qd-ttg.pdf",
    external: true,
    body: [
      "Quyết định số 749/QĐ-TTg ngày 03/6/2020 của Thủ tướng Chính phủ phê duyệt Chương trình Chuyển đổi số quốc gia đến năm 2025, định hướng đến năm 2030.",
      "Chương trình xác định mục tiêu kép: phát triển Chính phủ số, kinh tế số, xã hội số, đồng thời hình thành các doanh nghiệp công nghệ số Việt Nam có năng lực đi ra toàn cầu.",
    ],
    downloadCount: 1876,
  },
  {
    number: "127/QĐ-TTg",
    title: "Quyết định ban hành Chiến lược quốc gia về nghiên cứu, phát triển và ứng dụng Trí tuệ nhân tạo đến năm 2030",
    docType: "Quyết định",
    docGroup: "direction",
    issuer: "Thủ tướng Chính phủ",
    signer: null,
    issuedDate: "2021-01-26",
    effectiveDate: "2021-01-26",
    field: "tri-tue-nhan-tao",
    summary: "Đẩy mạnh nghiên cứu, phát triển và ứng dụng trí tuệ nhân tạo, đưa trí tuệ nhân tạo trở thành lĩnh vực công nghệ quan trọng của Việt Nam trong cuộc Cách mạng công nghiệp lần thứ tư.",
    fileName: "quyet-dinh-127-qd-ttg.pdf",
    external: true,
    body: [
      "Quyết định số 127/QĐ-TTg ngày 26/01/2021 của Thủ tướng Chính phủ ban hành Chiến lược quốc gia về nghiên cứu, phát triển và ứng dụng Trí tuệ nhân tạo đến năm 2030.",
      "Chiến lược hướng tới đưa trí tuệ nhân tạo trở thành lĩnh vực công nghệ quan trọng của Việt Nam, góp phần phát triển kinh tế – xã hội và bảo đảm quốc phòng, an ninh.",
    ],
    downloadCount: 1402,
  },
  {
    number: "13/2023/NĐ-CP",
    title: "Nghị định về bảo vệ dữ liệu cá nhân",
    docType: "Nghị định",
    docGroup: "legal",
    issuer: "Chính phủ",
    signer: null,
    issuedDate: "2023-04-17",
    effectiveDate: "2023-07-01",
    field: "du-lieu",
    summary: "Quy định về bảo vệ dữ liệu cá nhân và trách nhiệm bảo vệ dữ liệu cá nhân của cơ quan, tổ chức, cá nhân có liên quan.",
    fileName: "nghi-dinh-13-2023-nd-cp.pdf",
    external: true,
    body: [
      "Nghị định số 13/2023/NĐ-CP ngày 17/4/2023 của Chính phủ về bảo vệ dữ liệu cá nhân, có hiệu lực từ ngày 01/7/2023.",
      "Nghị định quy định về bảo vệ dữ liệu cá nhân và trách nhiệm bảo vệ dữ liệu cá nhân của cơ quan, tổ chức, cá nhân có liên quan.",
    ],
    downloadCount: 1158,
  },
  {
    number: "125/TB-NIDIT",
    title: "Thông báo tuyển dụng viên chức năm 2026",
    docType: "Thông báo",
    docGroup: "direction",
    issuer: INSTITUTE,
    signer: "Quyền Viện trưởng Nguyễn Thị Ngọc Trang",
    issuedDate: "2026-10-03",
    effectiveDate: null,
    field: null,
    summary: "Thông báo tuyển dụng 12 chỉ tiêu viên chức các vị trí nghiên cứu viên trí tuệ nhân tạo, kỹ sư dữ liệu, kỹ sư kiểm thử và chuyên viên quản lý khoa học.",
    fileName: "thong-bao-tuyen-dung-vien-chuc-2026.pdf",
    external: false,
    body: [
      "Căn cứ nhu cầu vị trí việc làm và chỉ tiêu biên chế được giao, Viện Công nghệ số và Chuyển đổi số quốc gia thông báo tuyển dụng viên chức năm 2026.",
      "Chỉ tiêu: Nghiên cứu viên trí tuệ nhân tạo (04); Kỹ sư dữ liệu (03); Kỹ sư kiểm thử, đánh giá an toàn thông tin (03); Chuyên viên quản lý khoa học (02).",
      "Thời hạn nhận hồ sơ: đến hết ngày 31/10/2026 tại Văn phòng Viện.",
    ],
    downloadCount: 534,
  },
  {
    number: "01/HD-NIDIT",
    title: "Hướng dẫn tra cứu, đăng ký và khai thác Danh mục dữ liệu phục vụ AI",
    docType: "Hướng dẫn",
    docGroup: "guidance",
    issuer: INSTITUTE,
    signer: "Phó Viện trưởng Trần Quốc Hưng",
    issuedDate: "2026-09-28",
    effectiveDate: "2026-10-01",
    field: "du-lieu",
    project: "khung-kien-truc-du-lieu-mo-phuc-vu-ai",
    summary: "Hướng dẫn mức truy cập, phương thức truy cập (tải tệp, API, lưu trữ đối tượng), hồ sơ đăng ký và quy trình phê duyệt khai thác dữ liệu.",
    fileName: "huong-dan-khai-thac-du-lieu-ai.pdf",
    external: false,
    body: [
      "1. Mức truy cập: Mở – tải trực tiếp, không cần đăng ký; Cần đăng ký – Viện cấp thông tin truy cập qua email; Hạn chế – chỉ cung cấp cho nghiên cứu được Hội đồng dữ liệu phê duyệt.",
      "2. Phương thức truy cập: tải tệp (CSV, JSON…), giao diện lập trình ứng dụng (API) và lưu trữ đối tượng tương thích S3.",
      "3. Hồ sơ đăng ký gồm: thông tin đơn vị, mục đích sử dụng, phạm vi dữ liệu, cam kết tuân thủ điều kiện sử dụng.",
      "4. Thời gian xử lý: 03 ngày làm việc với dữ liệu cần đăng ký; 10 ngày làm việc với dữ liệu hạn chế.",
    ],
    downloadCount: 389,
  },
  {
    number: "02/HD-NIDIT",
    title: "Hướng dẫn quy trình đăng ký dịch vụ đánh giá, thử nghiệm, kiểm định",
    docType: "Hướng dẫn",
    docGroup: "guidance",
    issuer: INSTITUTE,
    signer: "Phó Viện trưởng Lê Thị Minh Phương",
    issuedDate: "2026-08-15",
    effectiveDate: "2026-08-15",
    field: "danh-gia-kiem-dinh",
    summary: "Quy trình 4 bước: tiếp nhận yêu cầu, khảo sát và thống nhất phạm vi, thực hiện đánh giá, bàn giao báo cáo và khuyến nghị.",
    fileName: "huong-dan-dang-ky-danh-gia-kiem-dinh.pdf",
    external: false,
    body: [
      "Bước 1 – Tiếp nhận yêu cầu: đơn vị gửi phiếu đăng ký trực tuyến hoặc công văn đề nghị; Viện phản hồi trong 02 ngày làm việc.",
      "Bước 2 – Khảo sát, thống nhất phạm vi, tiêu chí, kế hoạch và hồ sơ cần cung cấp.",
      "Bước 3 – Thực hiện đánh giá theo tiêu chuẩn, phương pháp đã thống nhất.",
      "Bước 4 – Bàn giao báo cáo kết quả, khuyến nghị khắc phục; hỗ trợ đánh giá lại khi có yêu cầu.",
    ],
    downloadCount: 276,
  },
  {
    number: "45/BC-NIDIT",
    title: "Báo cáo kết quả hoạt động 6 tháng đầu năm và nhiệm vụ trọng tâm 6 tháng cuối năm 2026",
    docType: "Báo cáo",
    docGroup: "report",
    issuer: INSTITUTE,
    signer: "Quyền Viện trưởng Nguyễn Thị Ngọc Trang",
    issuedDate: "2026-07-10",
    effectiveDate: null,
    field: null,
    summary: "Tổng hợp kết quả thực hiện nhiệm vụ khoa học và công nghệ, dịch vụ đánh giá – kiểm định, đào tạo, hợp tác và nhiệm vụ trọng tâm 6 tháng cuối năm.",
    fileName: "bao-cao-6-thang-dau-nam-2026.pdf",
    external: false,
    body: [
      "6 tháng đầu năm 2026, Viện triển khai 12 nhiệm vụ khoa học và công nghệ các cấp, công bố 9 bài báo khoa học, thực hiện 17 hợp đồng đánh giá, thử nghiệm.",
      "Nhiệm vụ trọng tâm 6 tháng cuối năm: nghiệm thu các nhiệm vụ kết thúc trong năm; vận hành Danh mục dữ liệu phục vụ AI; tổ chức Hội thảo quốc gia về trí tuệ nhân tạo có trách nhiệm.",
    ],
    downloadCount: 198,
  },
  {
    number: "12/BC-NIDIT",
    title: "Báo cáo Chuyển đổi số khu vực công 2025: Hiện trạng và khuyến nghị",
    docType: "Báo cáo",
    docGroup: "report",
    issuer: INSTITUTE,
    signer: "Quyền Viện trưởng Nguyễn Thị Ngọc Trang",
    issuedDate: "2025-12-20",
    effectiveDate: null,
    field: "chuyen-doi-so",
    summary: "Kết quả khảo sát, phân tích mức độ chuyển đổi số khu vực công; nhận diện điểm nghẽn về dữ liệu, nhân lực, hạ tầng và 12 nhóm khuyến nghị.",
    fileName: "bao-cao-chuyen-doi-so-khu-vuc-cong-2025.pdf",
    external: false,
    body: [
      "Báo cáo tổng hợp kết quả khảo sát, phân tích mức độ chuyển đổi số khu vực công năm 2025.",
      "Các điểm nghẽn chính: dữ liệu phân tán, thiếu chuẩn chung; quy trình nghiệp vụ chưa được thiết kế lại; thiếu chỉ số đo lường hiệu quả từ góc độ người dân.",
      "Báo cáo đề xuất 12 nhóm khuyến nghị, trong đó ưu tiên quản trị dữ liệu, phát triển nhân lực số và đánh giá hiệu quả phục vụ.",
    ],
    downloadCount: 865,
  },
  {
    number: "NIDIT-TR-2026-02",
    title: "Báo cáo kỹ thuật: Đánh giá chất lượng dữ liệu trong các hệ thống thông tin dùng chung",
    docType: "Báo cáo kỹ thuật",
    docGroup: "report",
    issuer: "Trung tâm Đánh giá, Thử nghiệm và Kiểm định",
    signer: null,
    issuedDate: "2026-05-18",
    effectiveDate: null,
    field: "danh-gia-kiem-dinh",
    summary: "Phương pháp đánh giá chất lượng dữ liệu theo các đặc tính đầy đủ, chính xác, nhất quán, kịp thời và kết quả áp dụng thử nghiệm.",
    fileName: "bao-cao-ky-thuat-chat-luong-du-lieu.pdf",
    external: false,
    body: [
      "Báo cáo trình bày phương pháp đánh giá chất lượng dữ liệu dựa trên mô hình ISO/IEC 25012 với các đặc tính: đầy đủ, chính xác, nhất quán, kịp thời, tin cậy.",
      "Kết quả áp dụng thử nghiệm cho thấy tỷ lệ bản ghi thiếu trường bắt buộc dao động 3–11%, chủ yếu do khác biệt quy trình cập nhật giữa các đơn vị.",
    ],
    downloadCount: 143,
  },
  {
    number: "TCCS 01:2026/NIDIT",
    title: "Tiêu chuẩn cơ sở: Hồ sơ siêu dữ liệu cho bộ dữ liệu huấn luyện trí tuệ nhân tạo",
    docType: "Tiêu chuẩn cơ sở",
    docGroup: "standard",
    issuer: INSTITUTE,
    signer: "Phó Viện trưởng Trần Quốc Hưng",
    issuedDate: "2026-06-30",
    effectiveDate: "2026-07-01",
    field: "du-lieu",
    project: "khung-kien-truc-du-lieu-mo-phuc-vu-ai",
    summary: "Quy định các trường siêu dữ liệu bắt buộc và khuyến nghị khi công bố bộ dữ liệu huấn luyện AI: nguồn gốc, quy trình gán nhãn, thiên lệch đã biết, mục đích sử dụng, điều kiện truy cập.",
    fileName: "tccs-01-2026-ho-so-sieu-du-lieu.pdf",
    external: false,
    body: [
      "Phạm vi: áp dụng cho các bộ dữ liệu do Viện xây dựng hoặc tiếp nhận để công bố trên Danh mục dữ liệu phục vụ AI.",
      "Trường bắt buộc: định danh, tiêu đề, mô tả, đơn vị công bố, giấy phép, mức truy cập, phương thức truy cập, định dạng, số bản ghi, phiên bản, ngày công bố.",
      "Trường khuyến nghị: quy trình gán nhãn, độ đồng thuận, thiên lệch đã biết, tác vụ AI phù hợp, cấu trúc trường dữ liệu.",
    ],
    downloadCount: 221,
  },
  {
    number: "TCCS 02:2026/NIDIT",
    title: "Tiêu chuẩn cơ sở: Tiêu chí đánh giá mô hình trí tuệ nhân tạo theo mức độ rủi ro",
    docType: "Tiêu chuẩn cơ sở",
    docGroup: "standard",
    issuer: INSTITUTE,
    signer: "Phó Viện trưởng Lê Thị Minh Phương",
    issuedDate: "2026-09-10",
    effectiveDate: "2026-10-01",
    field: "danh-gia-kiem-dinh",
    project: "cong-cu-danh-gia-do-tin-cay-mo-hinh-ai",
    summary: "Phân loại trường hợp sử dụng AI theo bốn mức rủi ro và quy định chiều sâu đánh giá tương ứng về độ chính xác, độ bền vững, tính công bằng, minh bạch và an toàn.",
    fileName: "tccs-02-2026-danh-gia-mo-hinh-ai.pdf",
    external: false,
    body: [
      "Mức rủi ro: thấp, trung bình, cao, không chấp nhận được – xác định theo tác động tiềm ẩn đối với quyền, lợi ích của người dân.",
      "Tiêu chí đánh giá: độ chính xác; độ bền vững trước dữ liệu nhiễu và tấn công đối kháng; tính công bằng; khả năng giải thích; an toàn và bảo vệ dữ liệu.",
      "Hệ thống mức rủi ro cao phải được đánh giá độc lập trước khi đưa vào sử dụng và giám sát định kỳ sau triển khai.",
    ],
    downloadCount: 187,
  },
  {
    number: "Mẫu 01/DL",
    title: "Mẫu phiếu đăng ký khai thác dữ liệu",
    docType: "Biểu mẫu",
    docGroup: "form",
    issuer: INSTITUTE,
    signer: null,
    issuedDate: "2026-09-28",
    effectiveDate: "2026-10-01",
    field: "du-lieu",
    summary: "Biểu mẫu dùng cho tổ chức, cá nhân đăng ký khai thác bộ dữ liệu ở mức cần đăng ký hoặc hạn chế.",
    fileName: "mau-01-phieu-dang-ky-khai-thac-du-lieu.pdf",
    external: false,
    body: [
      "1. Thông tin người đăng ký: họ và tên, đơn vị, chức danh, email, điện thoại.",
      "2. Bộ dữ liệu đề nghị khai thác, phiên bản, phạm vi dữ liệu.",
      "3. Mục đích sử dụng, đề tài nghiên cứu liên quan (nếu có).",
      "4. Cam kết: sử dụng đúng mục đích, không phân phối lại, không tái định danh, trích dẫn nguồn khi công bố kết quả.",
    ],
    downloadCount: 412,
  },
  {
    number: "Mẫu 02/ĐG",
    title: "Mẫu phiếu đăng ký đánh giá, thử nghiệm, kiểm định",
    docType: "Biểu mẫu",
    docGroup: "form",
    issuer: INSTITUTE,
    signer: null,
    issuedDate: "2026-08-15",
    effectiveDate: "2026-08-15",
    field: "danh-gia-kiem-dinh",
    summary: "Biểu mẫu dùng cho cơ quan, tổ chức, doanh nghiệp đăng ký dịch vụ đánh giá, thử nghiệm, kiểm định của Viện.",
    fileName: "mau-02-phieu-dang-ky-danh-gia.pdf",
    external: false,
    body: [
      "1. Thông tin đơn vị đề nghị: tên đơn vị, địa chỉ, người liên hệ.",
      "2. Đối tượng đánh giá: tên hệ thống, phần mềm, mô hình hoặc cơ sở dữ liệu; phiên bản; môi trường vận hành.",
      "3. Dịch vụ đề nghị, tiêu chuẩn áp dụng (nếu có), thời gian mong muốn.",
      "4. Hồ sơ kèm theo: tài liệu mô tả, tài liệu thiết kế, hướng dẫn sử dụng.",
    ],
    downloadCount: 236,
  },
  {
    number: "Mẫu 03/KHCN",
    title: "Mẫu thuyết minh đề xuất nhiệm vụ khoa học và công nghệ cấp cơ sở",
    docType: "Biểu mẫu",
    docGroup: "form",
    issuer: INSTITUTE,
    signer: null,
    issuedDate: "2026-09-30",
    effectiveDate: "2026-09-30",
    field: null,
    summary: "Biểu mẫu thuyết minh đề xuất nhiệm vụ khoa học và công nghệ cấp cơ sở năm 2027.",
    fileName: "mau-03-thuyet-minh-de-xuat-nhiem-vu.pdf",
    external: false,
    body: [
      "1. Tên nhiệm vụ, lĩnh vực, chủ nhiệm và đơn vị chủ trì.",
      "2. Tính cấp thiết, mục tiêu, nội dung nghiên cứu chính.",
      "3. Sản phẩm dự kiến, phương án ứng dụng kết quả.",
      "4. Thời gian thực hiện, kinh phí dự kiến.",
    ],
    downloadCount: 158,
  },
];
