import type { Block } from "./helpers";
import type { UserKey } from "./core";

export type SeedArticleStatus = "published" | "pending" | "changes_requested" | "draft" | "approved" | "scheduled" | "unpublished";

export interface SeedArticle {
  title: string;
  summary: string;
  body: Block[];
  category: string;
  lang?: "vi" | "en";
  image?: string;
  caption?: string;
  author: string;
  keywords: string[];
  tags?: string[];
  featured?: boolean;
  /** Số ngày trước hiện tại (âm = tương lai) */
  daysAgo: number;
  hour?: number;
  views?: number;
  event?: { inDays: number; hour: number; location: string };
  status?: SeedArticleStatus;
  createdBy: UserKey;
  reviewerNote?: string;
  origin?: "manual" | "crawler";
  sourceName?: string;
  sourceUrl?: string;
  unpublishInDays?: number;
}

const VENUE = "Hội trường Viện, Số 113 Trần Duy Hưng, phường Yên Hòa, Hà Nội";

export const ARTICLES: SeedArticle[] = [
  /* ------------------------------ Tin hoạt động ------------------------------ */
  {
    title: "Viện công bố Danh mục dữ liệu phục vụ phát triển trí tuệ nhân tạo",
    summary:
      "Danh mục phiên bản thử nghiệm gồm 8 bộ dữ liệu văn bản, tiếng nói, hình ảnh và chỉ số chuyển đổi số, được mô tả theo chuẩn siêu dữ liệu thống nhất với điều kiện khai thác công khai, minh bạch.",
    body: [
      "Ngày đầu tháng 10, Viện Công nghệ số và Chuyển đổi số quốc gia chính thức đưa vào thử nghiệm <strong>Danh mục dữ liệu phục vụ AI</strong> trên Trang thông tin điện tử. Đây là đầu mối để các nhóm nghiên cứu, trường đại học và doanh nghiệp tra cứu, đăng ký và khai thác các bộ dữ liệu do Viện xây dựng.",
      "Phiên bản đầu tiên gồm 8 bộ dữ liệu với tổng dung lượng hơn 300 GB, trải rộng từ kho ngữ liệu văn bản hành chính, dữ liệu hỏi – đáp về thủ tục hành chính, tiếng nói đa vùng miền đến ảnh tài liệu số hóa và bộ chỉ số chuyển đổi số địa phương.",
      { h: "Ba mức truy cập, ba phương thức kết nối" },
      "Mỗi bộ dữ liệu được gắn một trong ba mức truy cập: <em>mở</em> (tải trực tiếp, không cần đăng ký), <em>cần đăng ký</em> (Viện cấp thông tin truy cập qua email) và <em>hạn chế</em> (chỉ cung cấp cho nghiên cứu được phê duyệt). Người dùng có thể tải tệp, gọi API hoặc kết nối vùng lưu trữ đối tượng tương thích S3 tùy từng bộ dữ liệu.",
      {
        ul: [
          "Thông tin mô tả thống nhất: nguồn gốc, quy trình gán nhãn, giấy phép, tần suất cập nhật.",
          "Cấu trúc trường dữ liệu được công bố trước khi đăng ký.",
          "Tệp mẫu 25 bản ghi giúp người dùng đánh giá nhanh mức độ phù hợp.",
        ],
      },
      "Theo kế hoạch, đến hết năm 2026 Danh mục sẽ được bổ sung thêm các bộ dữ liệu về y tế, giáo dục và nông nghiệp, đồng thời kết nối với các nền tảng dữ liệu dùng chung theo quy định của Luật Dữ liệu.",
    ],
    category: "hoat-dong-nghien-cuu",
    image: "du-lieu-gan-nhan",
    caption: "Cán bộ Trung tâm Dữ liệu và Trí tuệ nhân tạo rà soát nhãn dữ liệu trước khi công bố. Ảnh minh họa.",
    author: "Phạm Thu Hà",
    keywords: ["dữ liệu", "trí tuệ nhân tạo", "dữ liệu mở", "danh mục dữ liệu"],
    tags: ["Dữ liệu mở", "AI"],
    featured: true,
    daysAgo: 1,
    hour: 9,
    views: 1840,
    createdBy: "ha",
  },
  {
    title: "Ký kết thỏa thuận hợp tác nghiên cứu, đào tạo về công nghệ số với các trường đại học kỹ thuật",
    summary:
      "Thỏa thuận giai đoạn 2026–2030 tập trung vào nghiên cứu chung, chia sẻ hạ tầng phòng thí nghiệm, thực tập cho sinh viên và đồng hướng dẫn nghiên cứu sinh.",
    body: [
      "Sáng 4/10, tại Hà Nội, Viện Công nghệ số và Chuyển đổi số quốc gia ký kết thỏa thuận hợp tác với một số trường đại học kỹ thuật trong nước về nghiên cứu, đào tạo và chuyển giao công nghệ số.",
      "Theo thỏa thuận, các bên sẽ cùng đề xuất và thực hiện nhiệm vụ khoa học và công nghệ các cấp trong các lĩnh vực trí tuệ nhân tạo, dữ liệu, an toàn thông tin; chia sẻ hạ tầng tính toán và dữ liệu nghiên cứu; tổ chức hội thảo, seminar chuyên đề định kỳ.",
      { h: "Gắn đào tạo với nhu cầu thực tiễn" },
      "Viện sẽ tiếp nhận sinh viên năm cuối, học viên cao học đến thực tập tại Phòng thí nghiệm Trí tuệ nhân tạo và Trung tâm Đánh giá, Thử nghiệm và Kiểm định; cán bộ nghiên cứu của Viện tham gia giảng dạy, đồng hướng dẫn luận văn, luận án.",
      "Đại diện lãnh đạo Viện cho biết, hợp tác với các cơ sở đào tạo là giải pháp quan trọng để phát triển đội ngũ nhân lực chất lượng cao, đáp ứng yêu cầu đột phá về khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia.",
    ],
    category: "hop-tac",
    image: "news-ky-ket",
    caption: "Lễ ký kết thỏa thuận hợp tác. Ảnh minh họa.",
    author: "Phạm Thu Hà",
    keywords: ["hợp tác", "đào tạo", "công nghệ số", "nhân lực số"],
    tags: ["Hợp tác"],
    featured: true,
    daysAgo: 3,
    hour: 10,
    views: 1210,
    createdBy: "ha",
  },
  {
    title: "Đưa vào vận hành Phòng thí nghiệm Trí tuệ nhân tạo phục vụ nghiên cứu và thử nghiệm mô hình",
    summary:
      "Phòng thí nghiệm được trang bị cụm máy chủ GPU, hệ thống lưu trữ dữ liệu và môi trường thử nghiệm biệt lập, phục vụ các nhóm nghiên cứu trong và ngoài Viện.",
    body: [
      "Viện Công nghệ số và Chuyển đổi số quốc gia vừa đưa vào vận hành Phòng thí nghiệm Trí tuệ nhân tạo, cung cấp hạ tầng tính toán hiệu năng cao cho nghiên cứu, huấn luyện và đánh giá mô hình.",
      "Phòng thí nghiệm gồm cụm máy chủ tăng tốc đồ họa, hệ thống lưu trữ dung lượng lớn và môi trường thử nghiệm biệt lập dành cho dữ liệu nhạy cảm. Các nhóm nghiên cứu có thể đăng ký sử dụng theo đợt, ưu tiên các đề tài thuộc lĩnh vực xử lý ngôn ngữ tự nhiên tiếng Việt, thị giác máy tính và AI có trách nhiệm.",
      { quote: "Phòng thí nghiệm không chỉ là nơi huấn luyện mô hình mà còn là nơi kiểm chứng mô hình trước khi đưa vào phục vụ người dân.", by: "Đại diện Trung tâm Dữ liệu và Trí tuệ nhân tạo" },
      "Trong năm đầu vận hành, phòng thí nghiệm ưu tiên phục vụ đề tài xây dựng kho ngữ liệu tiếng Việt hành chính và đề tài phát triển bộ công cụ đánh giá độ tin cậy của mô hình trí tuệ nhân tạo.",
    ],
    category: "hoat-dong-nghien-cuu",
    image: "news-phong-lab-ai",
    caption: "Phòng thí nghiệm Trí tuệ nhân tạo của Viện. Ảnh minh họa.",
    author: "Đỗ Quang Minh",
    keywords: ["trí tuệ nhân tạo", "phòng thí nghiệm", "hạ tầng tính toán"],
    tags: ["AI", "Hạ tầng nghiên cứu"],
    featured: true,
    daysAgo: 6,
    hour: 15,
    views: 1532,
    createdBy: "minh",
  },
  {
    title: "Hội nghị sơ kết công tác 9 tháng đầu năm, triển khai nhiệm vụ quý IV/2026",
    summary: "Viện hoàn thành đúng tiến độ phần lớn chỉ tiêu kế hoạch; quý IV tập trung nghiệm thu nhiệm vụ, hoàn thiện Danh mục dữ liệu và chuẩn bị Hội thảo quốc gia.",
    body: [
      "Ngày 5/10, Viện Công nghệ số và Chuyển đổi số quốc gia tổ chức Hội nghị sơ kết công tác 9 tháng đầu năm và triển khai nhiệm vụ quý IV/2026.",
      "Báo cáo tại Hội nghị cho thấy, 9 tháng qua Viện đã triển khai 12 nhiệm vụ khoa học và công nghệ các cấp, công bố 14 bài báo khoa học, thực hiện 26 hợp đồng đánh giá, thử nghiệm và tổ chức 18 khóa bồi dưỡng kỹ năng số với hơn 2.100 lượt học viên.",
      { h: "Nhiệm vụ trọng tâm quý IV" },
      {
        ul: [
          "Nghiệm thu đúng hạn các nhiệm vụ kết thúc trong năm 2026.",
          "Hoàn thiện, mở rộng Danh mục dữ liệu phục vụ AI.",
          "Tổ chức thành công Hội thảo quốc gia về trí tuệ nhân tạo có trách nhiệm trong khu vực công.",
          "Xây dựng kế hoạch khoa học và công nghệ năm 2027.",
        ],
      },
      "Hội nghị cũng thống nhất tăng cường công tác truyền thông, cập nhật thường xuyên kết quả nghiên cứu, dịch vụ của Viện trên Trang thông tin điện tử.",
    ],
    category: "tin-hoat-dong",
    image: "news-hoi-thao",
    caption: "Quang cảnh Hội nghị. Ảnh minh họa.",
    author: "Ban Biên tập",
    keywords: ["sơ kết", "kế hoạch", "nhiệm vụ khoa học"],
    daysAgo: 2,
    hour: 16,
    views: 694,
    createdBy: "ha",
  },
  {
    title: "Tập huấn kỹ năng số và an toàn thông tin cho cán bộ, công chức năm 2026",
    summary: "Khóa tập huấn kéo dài 3 ngày, trang bị kỹ năng khai thác nền tảng số, nhận diện lừa đảo trực tuyến và bảo vệ dữ liệu cá nhân trong công việc.",
    body: [
      "Trung tâm Tư vấn và Đào tạo chuyển đổi số của Viện vừa tổ chức khóa tập huấn kỹ năng số và an toàn thông tin cho hơn 120 cán bộ, công chức đến từ các cơ quan, đơn vị.",
      "Nội dung tập huấn gồm: khai thác hiệu quả các nền tảng số dùng chung, quản lý văn bản và hồ sơ điện tử, sử dụng công cụ trí tuệ nhân tạo tạo sinh an toàn, nhận diện các hình thức lừa đảo trực tuyến và bảo vệ dữ liệu cá nhân.",
      "Bên cạnh bài giảng, học viên được thực hành trên môi trường mô phỏng và làm bài kiểm tra cuối khóa. 96% học viên đạt yêu cầu và được cấp giấy chứng nhận.",
      "Năm 2026, Viện dự kiến tổ chức 24 khóa bồi dưỡng tương tự, ưu tiên cán bộ cấp xã sau khi sắp xếp đơn vị hành chính.",
    ],
    category: "dao-tao-tap-huan",
    image: "news-tap-huan",
    caption: "Học viên thực hành tại lớp tập huấn. Ảnh minh họa.",
    author: "Phạm Thu Hà",
    keywords: ["tập huấn", "kỹ năng số", "an toàn thông tin", "chuyển đổi số"],
    tags: ["Đào tạo"],
    daysAgo: 9,
    hour: 14,
    views: 876,
    createdBy: "ha",
  },
  {
    title: "Đoàn công tác của Viện làm việc với các địa phương thí điểm nền tảng đô thị thông minh",
    summary: "Đoàn khảo sát hiện trạng hạ tầng, dữ liệu và trao đổi phương án mở rộng nền tảng IoT giám sát hạ tầng đô thị sau giai đoạn thí điểm.",
    body: [
      "Từ ngày 22 đến 24/9, đoàn công tác của Viện đã làm việc với các địa phương tham gia thí điểm nền tảng IoT giám sát hạ tầng đô thị.",
      "Tại các buổi làm việc, đoàn khảo sát hiện trạng thiết bị cảm biến, đường truyền và trung tâm điều hành; ghi nhận các đề xuất về tích hợp dữ liệu với hệ thống quản lý đô thị hiện có.",
      "Hai bên thống nhất xây dựng phương án mở rộng theo hướng dùng chung nền tảng, chuẩn hóa dữ liệu cảm biến và bảo đảm an toàn thông tin ngay từ khâu thiết kế.",
    ],
    category: "hop-tac",
    image: "news-doan-cong-tac",
    caption: "Đoàn công tác khảo sát thực tế. Ảnh minh họa.",
    author: "Đỗ Quang Minh",
    keywords: ["đô thị thông minh", "IoT", "công nghệ số"],
    tags: ["Đô thị thông minh"],
    daysAgo: 12,
    hour: 11,
    views: 642,
    createdBy: "minh",
  },
  {
    title: "Nghiệm thu đề tài ứng dụng AI hỗ trợ sàng lọc hình ảnh y tế tuyến cơ sở",
    summary: "Mô hình đạt độ nhạy 92,4% trên tập kiểm tra độc lập; Hội đồng đánh giá cao quy trình thử nghiệm và cơ chế giám sát sau triển khai.",
    body: [
      "Hội đồng nghiệm thu cấp Bộ vừa đánh giá kết quả đề tài “Ứng dụng trí tuệ nhân tạo hỗ trợ sàng lọc hình ảnh y tế tại tuyến cơ sở” do Trung tâm Dữ liệu và Trí tuệ nhân tạo chủ trì.",
      "Sau hơn hai năm thực hiện, nhóm nghiên cứu đã xây dựng bộ dữ liệu 24.000 ảnh X-quang ngực ẩn danh có nhãn chuyên gia, phát triển mô hình học sâu hỗ trợ sàng lọc và thử nghiệm tại một số cơ sở y tế tuyến cơ sở.",
      "Kết quả, mô hình đạt độ nhạy 92,4% trên tập kiểm tra độc lập; thời gian đọc phim trung bình giảm khoảng 30% trong giai đoạn thử nghiệm, trong khi quyết định cuối cùng vẫn do bác sĩ đưa ra.",
      "Hội đồng thống nhất nghiệm thu đề tài, xếp loại Đạt và đề nghị tiếp tục đánh giá độc lập trước khi nhân rộng.",
    ],
    category: "hoat-dong-nghien-cuu",
    image: "y-te-so",
    caption: "Bác sĩ sử dụng phần mềm hỗ trợ đọc phim. Ảnh minh họa.",
    author: "Đỗ Quang Minh",
    keywords: ["trí tuệ nhân tạo", "y tế số", "nghiệm thu", "kiểm định"],
    tags: ["AI", "Y tế số"],
    daysAgo: 15,
    hour: 9,
    views: 1105,
    createdBy: "minh",
  },
  {
    title: "Làm việc với đoàn chuyên gia quốc tế về quản trị dữ liệu và AI có trách nhiệm",
    summary: "Hai bên chia sẻ kinh nghiệm xây dựng khung quản trị dữ liệu, đánh giá rủi ro AI và trao đổi khả năng hợp tác nghiên cứu chuẩn trao đổi dữ liệu y tế.",
    body: [
      "Viện Công nghệ số và Chuyển đổi số quốc gia đã tiếp và làm việc với đoàn chuyên gia quốc tế về quản trị dữ liệu và trí tuệ nhân tạo có trách nhiệm.",
      "Tại buổi làm việc, đại diện Viện giới thiệu Danh mục dữ liệu phục vụ AI, bộ công cụ đánh giá độ tin cậy mô hình đang phát triển và kế hoạch nghiên cứu chuẩn trao đổi dữ liệu y tế số.",
      "Các chuyên gia chia sẻ kinh nghiệm về khung quản trị dữ liệu, cơ chế chia sẻ dữ liệu an toàn và phương pháp đánh giá rủi ro AI theo các tiêu chuẩn quốc tế như ISO/IEC 42001.",
      "Hai bên thống nhất tiếp tục trao đổi để xây dựng đề xuất nhiệm vụ hợp tác giai đoạn 2027–2029.",
    ],
    category: "hop-tac",
    image: "news-hop-tac-quoc-te",
    caption: "Buổi làm việc với đoàn chuyên gia quốc tế. Ảnh minh họa.",
    author: "Phạm Thu Hà",
    keywords: ["hợp tác quốc tế", "quản trị dữ liệu", "dữ liệu", "trí tuệ nhân tạo"],
    tags: ["Hợp tác quốc tế"],
    daysAgo: 18,
    hour: 15,
    views: 723,
    createdBy: "ha",
  },
  {
    title: "Khai giảng khóa bồi dưỡng chuyên gia chuyển đổi số cho cán bộ cấp xã",
    summary: "Chương trình 6 tuần kết hợp trực tuyến và trực tiếp, giúp cán bộ cấp xã lập kế hoạch, triển khai và đánh giá hiệu quả chuyển đổi số tại địa phương.",
    body: [
      "Trung tâm Tư vấn và Đào tạo chuyển đổi số khai giảng khóa bồi dưỡng chuyên gia chuyển đổi số dành cho cán bộ cấp xã với 80 học viên.",
      "Chương trình gồm 6 chuyên đề: tư duy chuyển đổi số, kiến trúc chính quyền số cấp xã, dữ liệu và dịch vụ công trực tuyến, an toàn thông tin, truyền thông chuyển đổi số và đo lường hiệu quả.",
      "Học viên sẽ thực hiện bài tập lớn xây dựng kế hoạch chuyển đổi số cho chính địa phương mình, được giảng viên của Viện góp ý trực tiếp.",
    ],
    category: "dao-tao-tap-huan",
    image: "field-chuyen-doi-so",
    caption: "Khóa bồi dưỡng chuyên gia chuyển đổi số. Ảnh minh họa.",
    author: "Ban Biên tập",
    keywords: ["chuyển đổi số", "bồi dưỡng", "cấp xã"],
    tags: ["Đào tạo"],
    daysAgo: 21,
    hour: 8,
    views: 512,
    createdBy: "ha",
  },

  /* ------------------------------ Tin chuyên ngành ------------------------------ */
  {
    title: "Chuyển đổi số khu vực công: từ số hóa hồ sơ đến vận hành dựa trên dữ liệu",
    summary:
      "Số hóa mới là bước đầu. Giá trị của chuyển đổi số khu vực công nằm ở khả năng dùng dữ liệu để thiết kế lại quy trình, ra quyết định và đo lường hiệu quả phục vụ.",
    body: [
      "Những năm qua, các cơ quan nhà nước đã đạt nhiều kết quả trong số hóa hồ sơ, cung cấp dịch vụ công trực tuyến và kết nối các cơ sở dữ liệu quốc gia. Tuy nhiên, theo các chuyên gia của Viện, giai đoạn tới đòi hỏi bước chuyển căn bản: <strong>từ số hóa sang vận hành dựa trên dữ liệu</strong>.",
      { h: "Ba điểm nghẽn" },
      {
        ul: [
          "Dữ liệu còn phân tán, thiếu chuẩn chung, chất lượng chưa đồng đều.",
          "Quy trình nghiệp vụ được “điện tử hóa” nhưng chưa được thiết kế lại.",
          "Thiếu chỉ số đo lường hiệu quả từ góc độ người dân, doanh nghiệp.",
        ],
      },
      "Để tháo gỡ, cần coi dữ liệu là tài sản, có chủ quản rõ ràng và được đánh giá chất lượng định kỳ; đồng thời đo lường mức độ hài lòng, thời gian xử lý thực tế thay vì chỉ đếm số dịch vụ được đưa lên mạng.",
      "Nghị quyết số 57-NQ/TW của Bộ Chính trị về đột phá phát triển khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia đã xác định dữ liệu là tư liệu sản xuất chính. Đây là định hướng quan trọng để các cơ quan xây dựng lộ trình chuyển đổi số thực chất.",
    ],
    category: "chuyen-doi-so",
    image: "news-dich-vu-cong",
    caption: "Người dân thực hiện thủ tục hành chính trên nền tảng số. Ảnh minh họa.",
    author: "Hoàng Minh Tuấn",
    keywords: ["chuyển đổi số", "khu vực công", "dữ liệu", "dịch vụ công"],
    tags: ["Chính phủ số"],
    featured: true,
    daysAgo: 2,
    hour: 7,
    views: 2210,
    createdBy: "ha",
  },
  {
    title: "Mô hình ngôn ngữ lớn tiếng Việt: cơ hội và yêu cầu về dữ liệu chất lượng",
    summary: "Chất lượng và tính hợp pháp của dữ liệu huấn luyện là yếu tố quyết định để mô hình ngôn ngữ tiếng Việt có thể được sử dụng an toàn trong cơ quan nhà nước.",
    body: [
      "Sự phát triển nhanh của mô hình ngôn ngữ lớn mở ra cơ hội tự động hóa nhiều tác vụ hành chính: tóm tắt văn bản, hỗ trợ soạn thảo, trả lời câu hỏi của người dân. Tuy nhiên, phần lớn mô hình phổ biến hiện nay được huấn luyện chủ yếu trên dữ liệu tiếng Anh.",
      "Kết quả đánh giá ban đầu của Viện trên bộ dữ liệu văn bản hành chính cho thấy các mô hình mã nguồn mở hiểu tốt nội dung nhưng còn hạn chế khi soạn thảo đúng thể thức, dùng đúng thuật ngữ pháp lý.",
      { h: "Dữ liệu phải sạch, hợp pháp và được kiểm soát" },
      "Theo nhóm nghiên cứu, kho ngữ liệu phục vụ huấn luyện cần bảo đảm nguồn gốc rõ ràng, được loại bỏ thông tin cá nhân và có cơ chế cập nhật khi văn bản hết hiệu lực. Đây là định hướng của đề tài xây dựng kho ngữ liệu tiếng Việt hành chính mà Viện đang thực hiện.",
    ],
    category: "tri-tue-nhan-tao",
    image: "nghien-cuu-tieng-viet",
    caption: "Nhóm nghiên cứu xử lý ngôn ngữ tự nhiên tiếng Việt. Ảnh minh họa.",
    author: "Đỗ Quang Minh",
    keywords: ["trí tuệ nhân tạo", "mô hình ngôn ngữ lớn", "dữ liệu", "tiếng Việt"],
    tags: ["AI", "NLP"],
    daysAgo: 4,
    hour: 10,
    views: 1388,
    createdBy: "minh",
  },
  {
    title: "Luật Dữ liệu và yêu cầu chuẩn hóa dữ liệu dùng chung trong cơ quan nhà nước",
    summary: "Luật Dữ liệu có hiệu lực từ 01/7/2025 đặt ra yêu cầu cao hơn về quản trị, chất lượng và chia sẻ dữ liệu giữa các cơ quan nhà nước.",
    body: [
      "Luật Dữ liệu số 60/2024/QH15 được Quốc hội thông qua ngày 30/11/2024, có hiệu lực từ ngày 01/7/2025, là khung pháp lý quan trọng cho việc xây dựng, quản trị, chia sẻ và khai thác dữ liệu số.",
      "Đối với các cơ quan nhà nước, yêu cầu đặt ra không chỉ là có dữ liệu mà dữ liệu phải “đúng, đủ, sạch, sống”, được chuẩn hóa để có thể kết nối, chia sẻ và tái sử dụng.",
      { h: "Ưu tiên của các cơ quan" },
      {
        ul: [
          "Rà soát, lập danh mục dữ liệu và xác định chủ quản dữ liệu.",
          "Áp dụng chuẩn siêu dữ liệu, mã định danh thống nhất.",
          "Đánh giá chất lượng dữ liệu định kỳ trước khi chia sẻ.",
          "Bảo đảm an toàn, bảo vệ dữ liệu cá nhân trong toàn bộ vòng đời dữ liệu.",
        ],
      },
      "Viện sẵn sàng hỗ trợ các cơ quan, đơn vị đánh giá chất lượng dữ liệu và tư vấn xây dựng khung quản trị dữ liệu.",
    ],
    category: "du-lieu-so",
    image: "news-trung-tam-du-lieu",
    caption: "Hạ tầng trung tâm dữ liệu. Ảnh minh họa.",
    author: "Ban Biên tập",
    keywords: ["dữ liệu", "Luật Dữ liệu", "quản trị dữ liệu", "chuẩn hóa"],
    tags: ["Pháp luật", "Dữ liệu"],
    daysAgo: 8,
    hour: 9,
    views: 1654,
    createdBy: "ha",
  },
  {
    title: "Đô thị thông minh: bài toán kết nối dữ liệu cảm biến và nền tảng điều hành",
    summary: "Kinh nghiệm từ các mô hình thí điểm cho thấy chuẩn hóa dữ liệu cảm biến và thiết kế nền tảng mở là điều kiện để đô thị thông minh phát triển bền vững.",
    body: [
      "Nhiều địa phương đã đầu tư trung tâm điều hành đô thị thông minh. Tuy vậy, việc kết nối dữ liệu từ các hệ thống cảm biến do nhiều nhà cung cấp khác nhau vẫn là thách thức lớn.",
      "Từ kết quả dự án nền tảng IoT giám sát hạ tầng đô thị, nhóm nghiên cứu của Viện khuyến nghị áp dụng kiến trúc mở, chuẩn hóa định dạng dữ liệu cảm biến và tách lớp nền tảng khỏi lớp ứng dụng để tránh phụ thuộc vào một nhà cung cấp.",
      "Bên cạnh đó, an toàn thông tin cho thiết bị IoT cần được tính đến ngay từ khâu thiết kế, bởi mỗi thiết bị kết nối đều có thể trở thành điểm yếu của hệ thống.",
    ],
    category: "chuyen-doi-so",
    image: "news-thanh-pho-thong-minh",
    caption: "Đô thị thông minh vận hành dựa trên dữ liệu. Ảnh minh họa.",
    author: "Phan Văn Long",
    keywords: ["đô thị thông minh", "IoT", "công nghệ số", "chuyển đổi số"],
    tags: ["Đô thị thông minh"],
    daysAgo: 11,
    hour: 8,
    views: 934,
    createdBy: "minh",
  },
  {
    title: "Đánh giá rủi ro hệ thống trí tuệ nhân tạo: xu hướng quốc tế và gợi mở cho Việt Nam",
    summary: "Tiếp cận dựa trên rủi ro đang trở thành xu hướng chung trong quản lý AI; đánh giá độc lập trước triển khai là công cụ quan trọng để xây dựng niềm tin.",
    body: [
      "Trên thế giới, quản lý trí tuệ nhân tạo đang dịch chuyển sang tiếp cận dựa trên rủi ro: mức độ kiểm soát tương xứng với tác động tiềm ẩn của hệ thống đối với con người và xã hội.",
      "Các khung tham chiếu như tiêu chuẩn ISO/IEC 42001:2023 về hệ thống quản lý AI hay Khung quản lý rủi ro AI (AI RMF 1.0) của Viện Tiêu chuẩn và Công nghệ quốc gia Hoa Kỳ (NIST) đều nhấn mạnh việc nhận diện, đo lường và giám sát rủi ro trong suốt vòng đời hệ thống.",
      { h: "Gợi mở cho Việt Nam" },
      "Theo các chuyên gia của Viện, cơ quan nhà nước khi triển khai chatbot, trợ lý ảo hay hệ thống hỗ trợ ra quyết định nên được đánh giá độc lập về độ chính xác, thiên lệch, khả năng bị tấn công và rò rỉ dữ liệu trước khi đưa vào sử dụng.",
      "Bộ công cụ đánh giá độ tin cậy của mô hình AI mà Viện đang phát triển hướng tới đáp ứng yêu cầu này.",
    ],
    category: "tri-tue-nhan-tao",
    image: "field-tri-tue-nhan-tao",
    caption: "Đánh giá mô hình trí tuệ nhân tạo. Ảnh minh họa.",
    author: "Lê Thị Minh Phương",
    keywords: ["trí tuệ nhân tạo", "đánh giá rủi ro", "kiểm định", "AI có trách nhiệm"],
    tags: ["AI", "Kiểm định"],
    daysAgo: 14,
    hour: 10,
    views: 1192,
    createdBy: "minh",
  },
  {
    title: "An toàn thông tin là điều kiện tiên quyết của chuyển đổi số bền vững",
    summary: "Mỗi hệ thống được đưa lên môi trường số đều cần được đánh giá an toàn thông tin theo cấp độ và giám sát liên tục.",
    body: [
      "Chuyển đổi số càng sâu rộng, bề mặt tấn công càng mở rộng. Các sự cố lộ lọt dữ liệu, mã độc tống tiền cho thấy an toàn thông tin phải được coi là điều kiện tiên quyết chứ không phải hạng mục bổ sung.",
      "Theo kinh nghiệm đánh giá của Trung tâm Đánh giá, Thử nghiệm và Kiểm định, các lỗ hổng phổ biến vẫn là cấu hình mặc định, phần mềm chưa cập nhật bản vá và kiểm soát truy cập lỏng lẻo.",
      {
        ul: [
          "Phân loại, xác định cấp độ an toàn cho từng hệ thống thông tin.",
          "Đánh giá, kiểm tra định kỳ và trước khi đưa vào vận hành.",
          "Giám sát, ứng cứu sự cố 24/7; diễn tập thường xuyên.",
        ],
      },
    ],
    category: "tin-chuyen-nganh",
    image: "news-an-toan-thong-tin",
    caption: "Giám sát an toàn thông tin. Ảnh minh họa.",
    author: "Ban Biên tập",
    keywords: ["an toàn thông tin", "chuyển đổi số", "kiểm định"],
    tags: ["An toàn thông tin"],
    daysAgo: 16,
    hour: 14,
    views: 987,
    createdBy: "ha",
  },
  {
    title: "Gán nhãn dữ liệu: công đoạn thầm lặng quyết định chất lượng mô hình AI",
    summary: "Quy trình gán nhãn có kiểm soát, đo độ đồng thuận và rà soát chéo giúp nâng cao chất lượng dữ liệu huấn luyện, giảm thiên lệch của mô hình.",
    body: [
      "Phía sau mỗi mô hình trí tuệ nhân tạo là hàng trăm nghìn mẫu dữ liệu được gán nhãn thủ công. Nhãn sai hoặc thiếu nhất quán sẽ dẫn tới mô hình dự đoán sai, thậm chí thiên lệch.",
      "Tại Trung tâm Dữ liệu và Trí tuệ nhân tạo, mỗi mẫu dữ liệu được ít nhất hai người gán nhãn độc lập; các trường hợp không thống nhất được chuyên gia phân xử. Độ đồng thuận được đo bằng hệ số Cohen's kappa và công bố cùng bộ dữ liệu.",
      "Hướng dẫn gán nhãn, mô tả các thiên lệch đã biết cũng được công bố trong thông tin mô tả của từng bộ dữ liệu trên Danh mục dữ liệu phục vụ AI.",
    ],
    category: "du-lieu-so",
    image: "field-du-lieu",
    caption: "Quy trình kiểm soát chất lượng dữ liệu. Ảnh minh họa.",
    author: "Bùi Thị Lan Anh",
    keywords: ["dữ liệu", "gán nhãn", "trí tuệ nhân tạo", "chất lượng dữ liệu"],
    tags: ["Dữ liệu"],
    daysAgo: 19,
    hour: 9,
    views: 845,
    createdBy: "minh",
  },
  {
    title: "Hạ tầng IoT cho nông nghiệp và môi trường: kinh nghiệm từ các mô hình thí điểm",
    summary: "Chi phí thiết bị giảm mạnh mở ra cơ hội ứng dụng IoT rộng rãi, nhưng vận hành, bảo trì và khai thác dữ liệu mới là yếu tố quyết định hiệu quả.",
    body: [
      "Cảm biến độ ẩm đất, trạm quan trắc môi trường hay thiết bị đo mực nước ngày càng rẻ và dễ triển khai. Tuy nhiên, nhiều mô hình thí điểm dừng lại sau khi hết kinh phí do thiếu kế hoạch vận hành dài hạn.",
      "Các chuyên gia khuyến nghị lựa chọn công nghệ kết nối phù hợp với địa hình, thiết kế nền tảng dùng chung để giảm chi phí và quan trọng nhất là xác định rõ ai sử dụng dữ liệu, sử dụng để làm gì.",
    ],
    category: "chuyen-doi-so",
    image: "ha-tang-iot",
    caption: "Thiết bị IoT quan trắc môi trường. Ảnh minh họa.",
    author: "Phan Văn Long",
    keywords: ["IoT", "nông nghiệp số", "công nghệ số", "môi trường"],
    tags: ["IoT"],
    daysAgo: 24,
    hour: 10,
    views: 611,
    createdBy: "minh",
  },
  {
    title: "Ứng dụng AI trong y tế cơ sở cần đi kèm cơ chế kiểm định độc lập",
    summary: "AI có thể giúp giảm tải cho y tế tuyến cơ sở, nhưng chỉ nên được triển khai rộng sau khi được kiểm định độc lập và có cơ chế giám sát liên tục.",
    body: [
      "Các mô hình AI hỗ trợ chẩn đoán hình ảnh có thể giúp bác sĩ tuyến cơ sở phát hiện sớm bất thường. Tuy nhiên, hiệu năng của mô hình có thể suy giảm khi áp dụng với thiết bị, quần thể bệnh nhân khác với dữ liệu huấn luyện.",
      "Vì vậy, cần đánh giá độc lập trên dữ liệu đại diện cho nơi triển khai, theo dõi hiệu năng sau triển khai và luôn bảo đảm vai trò quyết định cuối cùng của bác sĩ.",
    ],
    category: "tri-tue-nhan-tao",
    image: "field-danh-gia-kiem-dinh",
    caption: "Kiểm định mô hình AI trước triển khai. Ảnh minh họa.",
    author: "Nguyễn Hải Yến",
    keywords: ["trí tuệ nhân tạo", "y tế số", "kiểm định"],
    tags: ["AI", "Y tế số"],
    daysAgo: 27,
    hour: 15,
    views: 702,
    createdBy: "minh",
  },

  /* ------------------------------ Sự kiện – Hội thảo ------------------------------ */
  {
    title: "Sắp diễn ra Hội thảo quốc gia về trí tuệ nhân tạo có trách nhiệm trong khu vực công",
    summary:
      "Hội thảo quy tụ nhà quản lý, nhà khoa học và doanh nghiệp để thảo luận khung đánh giá, kiểm định và quản trị rủi ro khi ứng dụng AI tại cơ quan nhà nước.",
    body: [
      "Viện Công nghệ số và Chuyển đổi số quốc gia tổ chức Hội thảo quốc gia “Trí tuệ nhân tạo có trách nhiệm trong khu vực công”, dự kiến với sự tham dự của khoảng 300 đại biểu.",
      { h: "Các phiên thảo luận chính" },
      {
        ul: [
          "Phiên 1: Khung pháp lý và tiêu chuẩn quốc tế về quản trị AI.",
          "Phiên 2: Đánh giá, kiểm định mô hình AI trước khi triển khai.",
          "Phiên 3: Dữ liệu huấn luyện – chất lượng, bản quyền và bảo vệ dữ liệu cá nhân.",
          "Phiên 4: Chia sẻ kinh nghiệm triển khai trợ lý ảo, chatbot dịch vụ công.",
        ],
      },
      "Đại biểu đăng ký tham dự trực tuyến qua mục Liên hệ trên Trang thông tin điện tử của Viện. Hội thảo được truyền hình trực tuyến.",
    ],
    category: "su-kien-hoi-thao",
    image: "news-hoi-thao",
    caption: "Hội thảo khoa học do Viện tổ chức. Ảnh minh họa.",
    author: "Ban Biên tập",
    keywords: ["hội thảo", "trí tuệ nhân tạo", "AI có trách nhiệm", "kiểm định"],
    tags: ["Sự kiện", "AI"],
    featured: true,
    daysAgo: 1,
    hour: 14,
    views: 1460,
    event: { inDays: 15, hour: 8, location: VENUE },
    createdBy: "ha",
  },
  {
    title: "Tọa đàm chuyên đề: Kiểm định chất lượng phần mềm trong các dự án chuyển đổi số",
    summary: "Tọa đàm chia sẻ kinh nghiệm kiểm thử độc lập, tiêu chí nghiệm thu và các lỗi chất lượng thường gặp trong dự án công nghệ thông tin sử dụng vốn nhà nước.",
    body: [
      "Trung tâm Đánh giá, Thử nghiệm và Kiểm định tổ chức tọa đàm chuyên đề về kiểm định chất lượng phần mềm trong các dự án chuyển đổi số.",
      "Tọa đàm dành cho chủ đầu tư, ban quản lý dự án, đơn vị phát triển phần mềm, tập trung vào: lập kế hoạch kiểm thử từ sớm, tiêu chí chất lượng theo mô hình TCVN ISO/IEC 25010, kiểm thử hiệu năng và khả năng tiếp cận.",
      "Số lượng chỗ có hạn; đơn vị quan tâm vui lòng đăng ký trước qua email kiemdinh@nidit.gov.vn.",
    ],
    category: "su-kien-hoi-thao",
    image: "field-cong-nghe-so",
    caption: "Tọa đàm chuyên đề. Ảnh minh họa.",
    author: "Ban Biên tập",
    keywords: ["tọa đàm", "kiểm định", "chất lượng phần mềm", "chuyển đổi số"],
    tags: ["Sự kiện", "Kiểm định"],
    daysAgo: 3,
    hour: 9,
    views: 538,
    event: { inDays: 8, hour: 14, location: "Phòng họp tầng 5, " + VENUE },
    createdBy: "ha",
  },
  {
    title: "Diễn đàn Dữ liệu mở phục vụ nghiên cứu và đổi mới sáng tạo",
    summary: "Diễn đàn kết nối cơ quan nắm giữ dữ liệu, nhóm nghiên cứu và doanh nghiệp, thúc đẩy chia sẻ dữ liệu an toàn, đúng quy định.",
    body: [
      "Diễn đàn Dữ liệu mở là hoạt động thường niên do Viện khởi xướng, năm nay tập trung vào chủ đề chia sẻ dữ liệu phục vụ phát triển trí tuệ nhân tạo.",
      "Tại diễn đàn, Viện sẽ giới thiệu kết quả vận hành thử nghiệm Danh mục dữ liệu phục vụ AI, đồng thời lấy ý kiến về hồ sơ siêu dữ liệu và quy trình cấp quyền đối với dữ liệu hạn chế.",
    ],
    category: "su-kien-hoi-thao",
    image: "field-du-lieu",
    caption: "Diễn đàn Dữ liệu mở. Ảnh minh họa.",
    author: "Phạm Thu Hà",
    keywords: ["diễn đàn", "dữ liệu mở", "dữ liệu", "đổi mới sáng tạo"],
    tags: ["Sự kiện", "Dữ liệu mở"],
    daysAgo: 7,
    hour: 10,
    views: 489,
    event: { inDays: 36, hour: 8, location: VENUE },
    createdBy: "ha",
  },
  {
    title: "Toàn cảnh Hội thảo khoa học “Dữ liệu mở phục vụ phát triển AI”",
    summary: "Hơn 200 đại biểu tham dự; các tham luận thống nhất rằng dữ liệu chất lượng, hợp pháp là nền tảng để phát triển AI do Việt Nam làm chủ.",
    body: [
      "Hội thảo khoa học “Dữ liệu mở phục vụ phát triển AI” đã diễn ra với sự tham dự của hơn 200 đại biểu đến từ cơ quan quản lý, viện nghiên cứu, trường đại học và doanh nghiệp.",
      "12 tham luận được trình bày, tập trung vào kinh nghiệm xây dựng dữ liệu huấn luyện, chuẩn siêu dữ liệu, cơ chế chia sẻ và bảo vệ dữ liệu cá nhân.",
      "Kết luận hội thảo, các đại biểu kiến nghị sớm hình thành danh mục dữ liệu dùng chung phục vụ AI, có cơ chế phân loại mức truy cập rõ ràng. Kiến nghị này đã được Viện hiện thực hóa bằng Danh mục dữ liệu phục vụ AI phiên bản thử nghiệm.",
    ],
    category: "su-kien-hoi-thao",
    image: "news-phong-lab-ai",
    caption: "Đại biểu tham quan khu trình diễn công nghệ. Ảnh minh họa.",
    author: "Phạm Thu Hà",
    keywords: ["hội thảo", "dữ liệu mở", "trí tuệ nhân tạo", "dữ liệu"],
    tags: ["Sự kiện"],
    daysAgo: 19,
    hour: 18,
    views: 1036,
    event: { inDays: -19, hour: 8, location: VENUE },
    createdBy: "ha",
  },
  {
    title: "Hội nghị tập huấn triển khai Bộ chỉ số đánh giá chuyển đổi số",
    summary: "Hội nghị hướng dẫn phương pháp thu thập số liệu, tính toán chỉ số và sử dụng công cụ đánh giá trực tuyến cho các đơn vị tham gia thử nghiệm.",
    body: [
      "Viện tổ chức hội nghị tập huấn triển khai thử nghiệm Bộ chỉ số đánh giá mức độ chuyển đổi số cho đại diện các bộ, ngành, địa phương tham gia thử nghiệm.",
      "Đại biểu được hướng dẫn cách thu thập số liệu, cung cấp minh chứng và sử dụng công cụ đánh giá trực tuyến. Kết quả thử nghiệm sẽ là cơ sở hoàn thiện bộ chỉ số trước khi nghiệm thu đề tài.",
    ],
    category: "su-kien-hoi-thao",
    image: "news-tap-huan",
    caption: "Hội nghị tập huấn. Ảnh minh họa.",
    author: "Hoàng Minh Tuấn",
    keywords: ["bộ chỉ số", "chuyển đổi số", "tập huấn"],
    tags: ["Sự kiện"],
    daysAgo: 30,
    hour: 17,
    views: 744,
    event: { inDays: -30, hour: 8, location: VENUE },
    createdBy: "ha",
  },

  /* ------------------------------ Thông báo ------------------------------ */
  {
    title: "Thông báo mời đăng ký tham dự Hội thảo quốc gia về trí tuệ nhân tạo có trách nhiệm",
    summary: "Viện trân trọng kính mời các cơ quan, tổ chức, cá nhân quan tâm đăng ký tham dự và gửi tham luận trước ngày diễn ra Hội thảo 05 ngày.",
    body: [
      "Viện Công nghệ số và Chuyển đổi số quốc gia trân trọng kính mời đại diện các cơ quan, tổ chức, doanh nghiệp và nhà khoa học quan tâm đăng ký tham dự Hội thảo quốc gia “Trí tuệ nhân tạo có trách nhiệm trong khu vực công”.",
      { ul: ["Hình thức: trực tiếp kết hợp trực tuyến.", "Đăng ký: qua mục Liên hệ hoặc email hoithao@nidit.gov.vn.", "Tham luận: gửi bản tóm tắt không quá 500 từ."] },
      "Thông báo này tự động gỡ khỏi Trang sau khi Hội thảo kết thúc.",
    ],
    category: "thong-bao",
    image: "news-hoi-thao",
    author: "Văn phòng Viện",
    keywords: ["thông báo", "hội thảo", "trí tuệ nhân tạo"],
    daysAgo: 2,
    hour: 8,
    views: 403,
    unpublishInDays: 16,
    createdBy: "ha",
  },
  {
    title: "Thông báo tuyển dụng viên chức năm 2026",
    summary: "Viện tuyển dụng 12 chỉ tiêu viên chức nghiên cứu, kỹ sư dữ liệu, kỹ sư kiểm thử và chuyên viên; thời hạn nhận hồ sơ đến hết ngày 31/10/2026.",
    body: [
      "Căn cứ nhu cầu vị trí việc làm, Viện Công nghệ số và Chuyển đổi số quốc gia thông báo tuyển dụng viên chức năm 2026 như sau:",
      {
        ul: [
          "Nghiên cứu viên trí tuệ nhân tạo: 04 chỉ tiêu.",
          "Kỹ sư dữ liệu: 03 chỉ tiêu.",
          "Kỹ sư kiểm thử, đánh giá an toàn thông tin: 03 chỉ tiêu.",
          "Chuyên viên quản lý khoa học: 02 chỉ tiêu.",
        ],
      },
      "Hồ sơ gửi về Văn phòng Viện, Số 113 Trần Duy Hưng, phường Yên Hòa, thành phố Hà Nội. Chi tiết điều kiện, tiêu chuẩn xem tại tệp thông báo đính kèm trong mục Văn bản – Tài liệu.",
    ],
    category: "thong-bao",
    image: "gioi-thieu-tru-so",
    author: "Văn phòng Viện",
    keywords: ["tuyển dụng", "viên chức", "thông báo"],
    daysAgo: 4,
    hour: 8,
    views: 2950,
    createdBy: "ha",
  },
  {
    title: "Thông báo tiếp nhận đề xuất nhiệm vụ khoa học và công nghệ năm 2027",
    summary: "Các đơn vị, cá nhân gửi đề xuất nhiệm vụ khoa học và công nghệ cấp cơ sở năm 2027 về Phòng Quản lý khoa học và Hợp tác quốc tế trước ngày 15/11/2026.",
    body: [
      "Thực hiện kế hoạch khoa học và công nghệ năm 2027, Viện thông báo tiếp nhận đề xuất nhiệm vụ cấp cơ sở thuộc các lĩnh vực: công nghệ số, chuyển đổi số, dữ liệu, trí tuệ nhân tạo và đánh giá – thử nghiệm – kiểm định.",
      "Đề xuất lập theo mẫu, gửi bản điện tử về địa chỉ khoahoc@nidit.gov.vn. Hội đồng Khoa học và Đào tạo sẽ xem xét, xét chọn trong tháng 12/2026.",
    ],
    category: "thong-bao",
    image: "field-cong-nghe-so",
    author: "Phòng Quản lý khoa học và Hợp tác quốc tế",
    keywords: ["thông báo", "đề xuất nhiệm vụ", "khoa học công nghệ"],
    daysAgo: 10,
    hour: 8,
    views: 588,
    createdBy: "ha",
  },
  {
    title: "Thông báo vận hành thử nghiệm Danh mục dữ liệu phục vụ AI",
    summary: "Trong thời gian thử nghiệm, người dùng có thể góp ý về thông tin mô tả, phương thức truy cập và quy trình đăng ký khai thác dữ liệu.",
    body: [
      "Viện thông báo vận hành thử nghiệm Danh mục dữ liệu phục vụ AI trên Trang thông tin điện tử. Trong thời gian thử nghiệm, một số bộ dữ liệu chỉ cung cấp tệp mẫu.",
      "Mọi góp ý xin gửi về Trung tâm Dữ liệu và Trí tuệ nhân tạo qua email dulieu@nidit.gov.vn hoặc mục Liên hệ.",
    ],
    category: "thong-bao",
    image: "field-du-lieu",
    author: "Trung tâm Dữ liệu và Trí tuệ nhân tạo",
    keywords: ["thông báo", "dữ liệu", "danh mục dữ liệu"],
    daysAgo: 13,
    hour: 8,
    views: 467,
    createdBy: "minh",
  },

  /* ------------------------------ Bài đang trong quy trình ------------------------------ */
  {
    title: "Viện tham gia Triển lãm Công nghệ số và Đổi mới sáng tạo 2026",
    summary: "Gian trưng bày của Viện giới thiệu Danh mục dữ liệu phục vụ AI, bộ công cụ đánh giá mô hình và nền tảng IoT giám sát hạ tầng đô thị.",
    body: [
      "Viện Công nghệ số và Chuyển đổi số quốc gia tham gia Triển lãm Công nghệ số và Đổi mới sáng tạo 2026 với gian trưng bày giới thiệu các kết quả nghiên cứu tiêu biểu.",
      "Khách tham quan được trải nghiệm trực tiếp công cụ đánh giá mô hình AI và tra cứu Danh mục dữ liệu phục vụ AI.",
    ],
    category: "tin-hoat-dong",
    image: "news-doan-cong-tac",
    author: "Phạm Thu Hà",
    keywords: ["triển lãm", "đổi mới sáng tạo", "công nghệ số"],
    daysAgo: 0,
    hour: 9,
    status: "pending",
    createdBy: "ha",
  },
  {
    title: "Công bố kết quả thử nghiệm bộ công cụ đánh giá độ tin cậy mô hình AI",
    summary: "Phiên bản thử nghiệm của bộ công cụ đã được áp dụng đánh giá 6 mô hình ngôn ngữ và 3 mô hình thị giác máy tính.",
    body: [
      "Nhóm nghiên cứu đề tài phát triển bộ công cụ đánh giá an toàn và độ tin cậy của mô hình trí tuệ nhân tạo đã hoàn thành phiên bản thử nghiệm.",
      "Bộ công cụ gồm hơn 40 kịch bản kiểm thử tự động về độ chính xác, tính công bằng, khả năng chống tấn công đối kháng và rò rỉ dữ liệu.",
    ],
    category: "hoat-dong-nghien-cuu",
    image: "field-danh-gia-kiem-dinh",
    author: "Đỗ Quang Minh",
    keywords: ["kiểm định", "trí tuệ nhân tạo", "đánh giá mô hình"],
    daysAgo: 1,
    hour: 16,
    status: "pending",
    createdBy: "minh",
  },
  {
    title: "Bản tin chuyển đổi số tháng 9/2026: nhiều chuyển biến tích cực trong cung cấp dịch vụ công trực tuyến",
    summary: "Tổng hợp các sự kiện, số liệu và chính sách đáng chú ý về chuyển đổi số trong tháng 9/2026.",
    body: ["Bản tin tổng hợp các sự kiện, số liệu đáng chú ý về chuyển đổi số trong tháng.", "(Bản nháp – đang bổ sung số liệu)"],
    category: "chuyen-doi-so",
    image: "news-dich-vu-cong",
    author: "Phạm Thu Hà",
    keywords: ["bản tin", "chuyển đổi số"],
    daysAgo: 2,
    hour: 11,
    status: "changes_requested",
    reviewerNote: "Đề nghị bổ sung nguồn số liệu ở đoạn 2, rút gọn tiêu đề dưới 90 ký tự.",
    createdBy: "ha",
  },
  {
    title: "Hướng dẫn đăng ký khai thác dữ liệu dành cho nhóm nghiên cứu",
    summary: "Các bước đăng ký, hồ sơ cần chuẩn bị và thời gian xử lý yêu cầu khai thác dữ liệu.",
    body: ["Bài viết hướng dẫn từng bước đăng ký khai thác dữ liệu trên Danh mục dữ liệu phục vụ AI.", "(Bản nháp)"],
    category: "du-lieu-so",
    author: "Đỗ Quang Minh",
    keywords: ["hướng dẫn", "dữ liệu", "đăng ký"],
    daysAgo: 0,
    hour: 10,
    status: "draft",
    createdBy: "minh",
  },
  {
    title: "Ra mắt chuyên trang Đánh giá – Thử nghiệm – Kiểm định",
    summary: "Chuyên trang giới thiệu danh mục dịch vụ, tiêu chuẩn áp dụng và quy trình đăng ký đánh giá, thử nghiệm, kiểm định của Viện.",
    body: [
      "Chuyên trang Đánh giá – Thử nghiệm – Kiểm định trên Trang thông tin điện tử của Viện giới thiệu 5 nhóm dịch vụ, tiêu chuẩn áp dụng và quy trình đăng ký trực tuyến.",
      "Tổ chức, doanh nghiệp có thể gửi yêu cầu trực tuyến và nhận phản hồi trong 02 ngày làm việc.",
    ],
    category: "tin-hoat-dong",
    image: "field-danh-gia-kiem-dinh",
    author: "Phạm Thu Hà",
    keywords: ["kiểm định", "dịch vụ", "đánh giá"],
    daysAgo: 1,
    hour: 10,
    status: "approved",
    createdBy: "ha",
  },
  {
    title: "Công bố Báo cáo thường niên về chuyển đổi số khu vực công 2026",
    summary: "Báo cáo phân tích mức độ chuyển đổi số khu vực công và đề xuất 10 nhóm giải pháp cho năm 2027.",
    body: [
      "Viện công bố Báo cáo thường niên về chuyển đổi số khu vực công 2026, tổng hợp kết quả khảo sát và phân tích dữ liệu từ các bộ, ngành, địa phương.",
      "Báo cáo đề xuất 10 nhóm giải pháp, trong đó nhấn mạnh quản trị dữ liệu, phát triển nhân lực số và đánh giá hiệu quả từ góc độ người dân.",
    ],
    category: "tin-hoat-dong",
    image: "field-chuyen-doi-so",
    author: "Ban Biên tập",
    keywords: ["báo cáo", "chuyển đổi số", "khu vực công"],
    daysAgo: -1,
    hour: 8,
    status: "scheduled",
    createdBy: "ha",
  },
  {
    title: "Thông báo điều chỉnh thời gian tổ chức tọa đàm chuyên đề tháng 9",
    summary: "Tọa đàm chuyên đề tháng 9 được lùi lịch; thông báo đã hết hiệu lực.",
    body: ["Viện thông báo điều chỉnh thời gian tổ chức tọa đàm chuyên đề tháng 9. Thời gian mới sẽ được thông báo sau."],
    category: "thong-bao",
    author: "Văn phòng Viện",
    keywords: ["thông báo", "tọa đàm"],
    daysAgo: 26,
    hour: 8,
    status: "unpublished",
    createdBy: "ha",
  },
  {
    title: "Doanh nghiệp đẩy mạnh ứng dụng AI tạo sinh trong chăm sóc khách hàng",
    summary: "Tin tổng hợp từ nguồn RSS, chờ biên tập viên viết lại trước khi gửi duyệt.",
    body: [
      "<em>Tóm tắt từ nguồn:</em> Nhiều doanh nghiệp đang thử nghiệm trợ lý ảo dùng AI tạo sinh để trả lời khách hàng.",
      "<strong>Ghi chú biên tập:</strong> Tin được nhập từ nguồn RSS. Biên tập viên cần viết lại nội dung, kiểm chứng thông tin và ghi nguồn trước khi gửi duyệt; không sao chép nguyên văn bài gốc.",
    ],
    category: "tri-tue-nhan-tao",
    author: "Tin tổng hợp",
    keywords: ["AI tạo sinh", "trí tuệ nhân tạo"],
    daysAgo: 0,
    hour: 8,
    status: "draft",
    origin: "crawler",
    sourceName: "VnExpress – Khoa học Công nghệ",
    sourceUrl: "https://vnexpress.net/khoa-hoc-cong-nghe",
    createdBy: "minh",
  },

  /* ------------------------------ English ------------------------------ */
  {
    title: "NIDIT launches catalogue of datasets for AI research",
    summary: "The trial catalogue lists eight datasets covering text, speech, images and digital transformation indicators, each with standard metadata and clear access conditions.",
    body: [
      "The National Institute of Digital Technology and Digital Transformation has launched a trial <strong>catalogue of datasets for AI</strong> on its website, giving researchers, universities and businesses a single point to discover, request and use the Institute's datasets.",
      "Each dataset carries one of three access levels – open, registration required, or restricted – and is available via file download, API or S3-compatible object storage.",
      "More datasets in health, education and agriculture will be added by the end of 2026.",
    ],
    category: "hoat-dong-nghien-cuu",
    lang: "en",
    image: "du-lieu-gan-nhan",
    caption: "Data labelling quality review. Illustrative photo.",
    author: "Editorial Board",
    keywords: ["data", "artificial intelligence", "open data"],
    featured: true,
    daysAgo: 1,
    hour: 11,
    views: 312,
    createdBy: "ha",
  },
  {
    title: "Institute signs research and training agreements with technical universities",
    summary: "The 2026–2030 agreements cover joint research, shared laboratory infrastructure, student internships and co-supervision of PhD candidates.",
    body: [
      "The Institute has signed cooperation agreements with several Vietnamese technical universities on research, training and technology transfer in digital technology.",
      "The parties will jointly propose research projects in AI, data and cybersecurity, share compute and research data, and organise regular seminars.",
    ],
    category: "hop-tac",
    lang: "en",
    image: "news-ky-ket",
    author: "Editorial Board",
    keywords: ["cooperation", "training", "digital technology"],
    daysAgo: 3,
    hour: 12,
    views: 204,
    createdBy: "ha",
  },
  {
    title: "New AI laboratory opens for model training and evaluation",
    summary: "The laboratory provides GPU servers, large-scale storage and an isolated test environment for research teams inside and outside the Institute.",
    body: [
      "The Institute has opened its Artificial Intelligence Laboratory, offering high-performance compute for training and evaluating models.",
      "Priority in the first year goes to the Vietnamese administrative corpus project and the AI trustworthiness evaluation toolkit project.",
    ],
    category: "hoat-dong-nghien-cuu",
    lang: "en",
    image: "news-phong-lab-ai",
    author: "Editorial Board",
    keywords: ["artificial intelligence", "laboratory"],
    daysAgo: 6,
    hour: 16,
    views: 187,
    createdBy: "minh",
  },
  {
    title: "Public sector digital transformation: from digitised records to data-driven operations",
    summary: "Digitisation is only the first step. The real value lies in using data to redesign processes, inform decisions and measure service outcomes.",
    body: [
      "Government agencies have made strong progress in digitising records and delivering online public services. The next phase, according to the Institute's experts, requires a shift from digitisation to data-driven operations.",
      "That means treating data as an asset with clear ownership and regular quality assessment, and measuring citizen satisfaction and real processing times rather than counting online services.",
    ],
    category: "chuyen-doi-so",
    lang: "en",
    image: "news-dich-vu-cong",
    author: "Hoang Minh Tuan",
    keywords: ["digital transformation", "public sector", "data"],
    daysAgo: 2,
    hour: 9,
    views: 256,
    createdBy: "ha",
  },
  {
    title: "National workshop on responsible AI in the public sector",
    summary: "Policy makers, scientists and businesses will discuss frameworks for evaluating, testing and managing risks of AI used by government agencies.",
    body: [
      "The Institute will host a national workshop on responsible artificial intelligence in the public sector, expected to bring together around 300 participants.",
      "Sessions cover international governance standards, pre-deployment model evaluation, training data quality and lessons from public service chatbots.",
    ],
    category: "su-kien-hoi-thao",
    lang: "en",
    image: "news-hoi-thao",
    author: "Editorial Board",
    keywords: ["workshop", "responsible AI", "evaluation"],
    daysAgo: 1,
    hour: 15,
    views: 143,
    event: { inDays: 15, hour: 8, location: "Institute Hall, 113 Tran Duy Hung, Hanoi" },
    createdBy: "ha",
  },
  {
    title: "Information security as a precondition for sustainable digital transformation",
    summary: "Every system moved online should be assessed according to its security level and continuously monitored.",
    body: [
      "As digital transformation deepens, the attack surface grows. Data leaks and ransomware incidents show that security must be treated as a precondition, not an add-on.",
      "The Institute's testing centre finds that default configurations, unpatched software and weak access control remain the most common vulnerabilities.",
    ],
    category: "tin-chuyen-nganh",
    lang: "en",
    image: "news-an-toan-thong-tin",
    author: "Editorial Board",
    keywords: ["information security", "digital transformation"],
    daysAgo: 16,
    hour: 15,
    views: 98,
    createdBy: "ha",
  },
];
